version: '3.6'
services:
  db:
    image: patternpedia/initialized-pattern-atlas-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - default
networks:
  default:
    driver: bridge
