version: '3.6'
services:
  db:
    image: patternpedia/initialized-pattern-atlas-db:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PATTERN_ATLAS_CONTENT_REPOSITORY_URL: https://github.com/IAC2-Project/pattern-atlas-content.git
    ports:
      - "5432:5432"
    networks:
      - default
  pattern-pedia-api:
    image:  patternpedia/patternrepo-api:latest
    environment:
      JDBC_DATABASE_URL: db
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - db
    restart: on-failure
  pattern-pedia-ui:
    image: patternpedia/patternrepo-ui:latest
    depends_on:
      - config-server
    environment:
      # because the requests are performed from the browser and not
      # from the container itself we have to specify localhost here
      # and **not** the container name
      PATTERN_ATLAS_API_HOST_NAME: localhost
      PATTERN_ATLAS_API_PORT: 8080
      LATEX_RENDERER_HOST_NAME: localhost
      LATEX_RENDERER_PORT: 8082
    ports:
      - "4200:80"
  config-server:
    image: quay.io/coreos/etcd:latest
    environment:
      ETCD_NAME: config-node1
      ETCD_CORS: "*"
      ETCD_ADVERTISE_CLIENT_URLS: "http://config-server:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: 3
    ports:
      - "2379:2379"
    networks:
      - default
  # used by the pattern atlas to render latex
  latex-renderer:
    image: planqk/latex-renderer:v1.0.1
    ports:
      - "8083:8082"
networks:
  default:
    driver: bridge
