version: '3'
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - default
  pattern-pedia-api:
    image: patternpedia/patternrepo-api:latest
    environment:
      JDBC_DATABASE_URL: db
      JDBC_DATABASE_USERNAME: postgres
      JDBC_DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    networks:
      - default
  pattern-pedia-ui:
    image: patternpedia/patternrepo-ui:latest
    ports:
      - "4200:80"
networks:
  default:
    driver: bridge
